### ISSUE TITLE
linux支持

### ISSUE THREAD

**Issue by ghost** [givemefivw/SecurityServiceBox#2]
请问该项目支持linux吗？

**Comment by givemefivw** [comment]
暂时是不支持的。因为linux和win不同，暂时没找到linux下类似cmd /k的命令
但框架已经写好了，师傅如果想在linux运行只需要修改预期执行的命令就可以了

**Comment by ghost** [comment]
修改https://github.com/givemefivw/SecurityServiceBox/blob/main/lib/cmd/wanli.py 文件是吗

**Comment by ghost** [comment]
能否使用./代替cmd /k

**Comment by givemefivw** [comment]
对的，就是wanli.py的命令  ，可以替代
其实就相当于一个快捷方式
