### ISSUE TITLE
询问使用的文件资源管理器和右键菜单

### ISSUE THREAD

**Issue by DomnicLockhart** [givemefivw/SecurityServiceBox#4]
请问您使用的自定义的文件资源管理器和右键菜单是怎么弄的？

**Comment by givemefivw** [comment]
文件资源管理器是OneCommder：https://www.onecommander.com/
右键菜单其实是Onecom自带支持的，如果说你指的是右键菜单里面的  通过cmder打开  那么README文件里面有写

**Comment by DomnicLockhart** [comment]
好的，非常感谢您
