### ISSUE TITLE
当出现cmd相关报错解决

### ISSUE THREAD

**Issue by Jmdyy** [givemefivw/SecurityServiceBox#9]
1.没安装cmd2模块
2.源码lib下重名产生

**Comment by givemefivw** [comment]
师傅能否详细一些
比如何种系统 具体的报错信息 或者截图之类的

**Comment by Jmdyy** [comment]
main.py里面的第九行,在我电脑上会出现和自己的lib库重名产生冲突无法引入wanli,这个可能有特殊性,解决方法是改一下引用路径,截图没了上次用的时候出现的.
